<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>42638cba-fb2a-4f69-86fb-e8b01ab05c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal_banner']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-body-banner > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d85224d6-3e85-464d-9c17-7f277edb944a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rs-dev.promosindo.web.id//uploads/editor/images/243359573_10219567781575523_8732200365144067051_n.jpg</value>
      <webElementGuid>229c0caf-cd38-4e5d-a8c9-4a19aa8ae231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_banner&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body-banner&quot;]/img[1]</value>
      <webElementGuid>3c0f26cc-43f6-41e8-be9e-0c0f392a3481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_banner']/div/div/div/img</value>
      <webElementGuid>6a6e67f7-f5a1-4173-95a0-94dd3f2ba5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://rs-dev.promosindo.web.id//uploads/editor/images/243359573_10219567781575523_8732200365144067051_n.jpg')]</value>
      <webElementGuid>8a22fee2-5356-4d2f-856d-1d72a3f9c01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/img</value>
      <webElementGuid>eeb6289e-e42c-4b3e-a2a0-cd34ef8a1a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://rs-dev.promosindo.web.id//uploads/editor/images/243359573_10219567781575523_8732200365144067051_n.jpg']</value>
      <webElementGuid>f73ea839-1cc5-4383-b3bf-93cd64d3ef9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
