<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Gunakan Voucher</name>
   <tag></tag>
   <elementGuidId>e82f5710-3d28-4f7e-b217-1281af404105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_redeem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_redeem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c5a6c78-48a2-452c-8d9b-d58ab0d9ce99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-rose </value>
      <webElementGuid>e7b3c740-8f6b-45c4-8b80-cd6569a38152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_redeem</value>
      <webElementGuid>30268f85-f590-4500-9033-7fbe1f8c3f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gunakan Voucher</value>
      <webElementGuid>9d07f437-fa01-46ce-b92a-d4ec510d16e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_redeem&quot;)</value>
      <webElementGuid>01a85863-308f-4f7d-8b2d-6c9c2cfc70a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_redeem']</value>
      <webElementGuid>44284ced-dd03-4501-b5ec-e6a239173001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_add']/button</value>
      <webElementGuid>63ec8fd7-24f7-45f6-a20c-44cac01e81f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i'])[1]/following::button[1]</value>
      <webElementGuid>de2ea470-5046-4a3d-af9c-9baa4e88cabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::button[1]</value>
      <webElementGuid>ebd12ce5-4465-4603-9f8c-a836f0ccbade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[2]</value>
      <webElementGuid>c2f14a20-a27d-4777-861f-3dca420f20dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>6dfc213a-55db-404b-adb7-c83f8ebf0127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_redeem' and (text() = 'Gunakan Voucher' or . = 'Gunakan Voucher')]</value>
      <webElementGuid>2cbb7752-d8f3-4e3e-bb00-541b26c6584c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
