<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_keyboard_arrow_down</name>
   <tag></tag>
   <elementGuidId>5052871c-b7ac-4797-96c5-1b0206c00bcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion1']/div/div/div/div[2]/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-4 > h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d77d80c9-6daf-480c-892c-9b342ff943a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> keyboard_arrow_down</value>
      <webElementGuid>fc8a201e-548f-4fac-a99a-b0cfadc71e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion1&quot;)/div[@class=&quot;form-group has-default&quot;]/div[@class=&quot;mt-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-4&quot;]/h4[1]</value>
      <webElementGuid>6f3857af-4332-44db-be5d-cc691985826c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion1']/div/div/div/div[2]/h4</value>
      <webElementGuid>cc72e9e0-f1a5-4bdf-b056-7e046406764e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Virtual Account'])[1]/following::h4[1]</value>
      <webElementGuid>10b91f66-7e6b-4f12-87cc-9a69a351dae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bonus Saldo'])[1]/following::h4[3]</value>
      <webElementGuid>f2679d1b-211e-4037-abef-8575bb2d0178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QRIS (DANA, GOPAY, OVO, LINKAJA, SHOPEEPAY)'])[1]/preceding::h4[1]</value>
      <webElementGuid>d8045b28-ac32-44c3-899c-015580712ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div[2]/h4</value>
      <webElementGuid>58dbf9ff-c877-4034-a1cd-263033b324c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = ' keyboard_arrow_down' or . = ' keyboard_arrow_down')]</value>
      <webElementGuid>5c8f5d8a-314e-4697-a8fb-871f9efb8510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
