<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan Kode  Vocher_code_voucher_upgrade</name>
   <tag></tag>
   <elementGuidId>1ab2e079-f21b-4b5d-8bf3-9d0f35e8860b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#code_voucher_upgrade</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='code_voucher_upgrade']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>440d197b-c5da-47e2-87ed-17eee056b9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f83c569-7bd8-4bfb-8a55-12d5e8908dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code_voucher_upgrade</value>
      <webElementGuid>d397da9a-9182-4362-9b80-2e51fc4a6985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>code_voucher_upgrade</value>
      <webElementGuid>279d1ebf-0462-4cfb-9182-9384c102472f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3be03378-88c3-4f97-b6c1-760f897729b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;code_voucher_upgrade&quot;)</value>
      <webElementGuid>00a76166-17d4-4927-8e5d-311c8301e2fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='code_voucher_upgrade']</value>
      <webElementGuid>142e7dfb-c46f-4070-af15-c38a82ef0db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_add']/div/input</value>
      <webElementGuid>7957f89a-c025-4d74-9246-60995930d231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/form/div/input</value>
      <webElementGuid>59cbf473-5e05-400a-8a2c-d17653ba6d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code_voucher_upgrade' and @id = 'code_voucher_upgrade']</value>
      <webElementGuid>495f24dc-01f7-4392-8936-e70e017d3e4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
